### ISSUE TITLE
Update of package maptpx

### ISSUE THREAD

**Issue by pchopin971** [TaddyLab/maptpx#3]
Hello,

I would like to know if there is a way of using the function "topics" from the "maptpx" package anymore considering that the package is not usable now on R version 4.0.0 because of lack of updates. Could you re orientate me towards other solutions ? 
Thanks for your kind help.
Best regards,
Pierre

**Comment by mataddy** [comment]
Thanks Pierre, I am going to go into figure out what is not working and update it to fix.

**Comment by mataddy** [comment]
@kkdey we've been booted off of CRAN.  I don't have any messages from them, did you get any communications about what to fix?  I'm also looking at the code now; what function does the squarem dependency solve?  thanks

**Comment by kkdey** [comment]
Hi Matt,

Yes they removed my package from Bioc because maptpx was not on CRAN. I thought you probably removed it for some reason. I don't know the reason, but they recent moved to R 4.0 which is causing issues with most packages. I haven't been working in this space for some time, but if you decide to fix and put it back on CRAN, that would be great.

**Comment by mataddy** [comment]
cool, I will fix it to get it back up.  I've discovered people are using it now that it got kicked off of CRAN.  Is what is in GitHub the most recent that you submitted to CRAN?

**Comment by kkdey** [comment]
No, the version on Github was a more latest one compared to the CRAN. Some of the users who were using CountClust were installing the maptpx from Github already as it had a few additional fixes that were more compatible for larger data.

**Comment by mataddy** [comment]
ok cool.  I'll try to get this one up to where CRAN will take it back.

**Comment by mataddy** [comment]
The new package has been submitted to CRAN.  I had to revert back to the last CRAN version then fix the minor error (caused by an update to the slam package, and some new R guidelines on namespaces and native routine registration).  The new stuff including SQUAREM had other issues I couldn't diagnose.  @kkdey I left your work as a new branch in case you want to pick it up again.
